TypeError: sel.nativeSelection is null - Firefox
This solution was provided by this issue https://github.com/xing/wysihtml5/issues/371 but not implemented in this code, (it was implemented in the bootstrap version only

https://github.com/glebm/bootstrap-wysihtml5-rails/blob/master/vendor/assets/javascripts/bootstrap-wysihtml5/rangy/rangy-core.js#L2958